### ISSUE TITLE
Choose a RISC subset of x86_64

### ISSUE THREAD

**Issue by apt1002** [apt1002/mijit#3]
We want to generate x86_64 code directly into RAM, fast. We don't need to be able to assemble any x86_64 instruction. I think a small and fairly regular subset will suffice. Choose the subset and copy the necessary data from reference manuals into `doc/x86.md`. (The text which was previously here is now there).

- [x] Registers
- [x] Load and store instructions, of any width and signedness
- [x] Arithmetic, including move
- [x] Comparisons
- [x] Branches
- [x] Jumps
- [x] Calls, including calling conventions
- [x] Push and pop
- [x] Atomic operations (for reference counting)
- [ ] Testing and setting bits
- [x] Multiplication
- [x] Division
- [x] Conditional moves

**Comment by apt1002** [comment]
If we are content always to assemble a `SIB` byte when accessing memory, the differences between `R12` and other registers vanishes. This adds one byte of code per memory access. A good trade?

**Comment by rrthomas** [comment]
Would it be too terrible just to emit the extra byte when R12 is used?

**Comment by apt1002** [comment]
It wouldn't be terrible, no. It would be hidden in a black box, and it's probably less work than e.g. making separate methods for assembling `R12`-relative memory accesses. Maybe we should just do that.

Especially since we could do the same for `SP`-relative addressing. I recently realized that we're going to have to assemble instructions to add constants to `SP`; they could be unified too if `SP` is just another register. There are monsters in `push RSP` and `push [RSP]`, and similarly for `pop`, but I suppose it's not my problem if callers engage those monsters.

**Comment by apt1002** [comment]
Based on today's work, I've added multiplication, division and conditional moves to the list of requirements.

**Comment by apt1002** [comment]
Closing in favour of #8, #9 and #10.
